# Generated by Django 3.2.6 on 2021-09-22 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_box_boxtattribute_card_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('availability_status', models.BooleanField(default=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.box')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.size')),
            ],
            options={
                'verbose_name_plural': 'ProductAttributes',
            },
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='status',
            new_name='availability_status',
        ),
        migrations.AddField(
            model_name='card',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='BoxtAttribute',
        ),
    ]
