# Generated by Django 3.2.6 on 2021-09-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_auto_20210922_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='boxattribute',
            options={'verbose_name_plural': 'BoxAttributes'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': 'Cards'},
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
