# Generated by Django 3.2.6 on 2021-09-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_auto_20210922_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Size',
            new_name='BoxSize',
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': '4. Boxes'},
        ),
        migrations.AlterModelOptions(
            name='boxattribute',
            options={'verbose_name_plural': '5. BoxAttributes'},
        ),
        migrations.AlterModelOptions(
            name='boxsize',
            options={'verbose_name_plural': '3. Box Sizes'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': '6. Cards'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '7. Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '8. ProductAttributes'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name_plural': '2. Variants'},
        ),
    ]
